Global User Recommendation Feature Switch
tailorck/parqr-flask pull request #187
Opened 2021-05-20 04:02 UTC by tailorck

## Description

This is a new feature to allow for a global boolean to enable/disable all user recommendations

## Motivation and Context

We need a quick way to "turn off" parqr without disturbing data collection and admin dashboard

## How Has This Been Tested?

It hasn't

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have run the current suite of unit tests to make sure my code doesn't break anything

2021-05-20 04:21 UTC, RFinkelberg reviewed
LGTM but a few considerations:
1. Do we need to do this on a per class basis? Essentially support config files for each class with switches like these?
2. Will this affect the dashboard too? 
3. How is the frontend handling this change? Are we showing nothing, or will the UI look broken? We may need to send back a special response code if the switch is off, so the frontend knows what to do

2021-05-20 16:57 UTC, aspadiyath requested changes
I agree with roy on number 1, if we move on from the experiementing phase, we'll have to implement a system to check if the class should be on or off, rather than the whole system. Other than that, just one fix.

2021-05-20 16:57 UTC, aspadiyath commented on app/utils.py
> +            return {}, 200
Will throw an error in frontend the way this is written at the moment.

Will need to be:
```return {'message': 'success', 'recommendations': []}, 200```

2021-05-20 16:58 UTC, aspadiyath commented
> 2. Will this affect the dashboard too?
If we fix the code for my request, it should be fine.
> 3. How is the frontend handling this change? Are we showing nothing, or will the UI look broken? We may need to send back a special response code if the switch is off, so the frontend knows what to do
It just shows no posts, it looks fine.

2021-05-21 15:38 UTC, tailorck commented on app/utils.py
> +            return {}, 200
noted.

2021-05-21 18:22 UTC, aspadiyath approved these changes

2021-05-24 15:00 UTC, merged

2021-05-27 16:19 UTC, aspadiyath reviewed
Errors showing up in logs

2021-05-27 16:19 UTC, aspadiyath commented on app/utils.py
> +    def wrapper(*args, *kwargs):
Should be **kwargs

2021-05-27 16:19 UTC, aspadiyath commented on app/utils.py
> +    @wraps(func)
module initialization error: name 'wraps' is not defined